services:
  backend:
    environment:
      - PRIVATE_KEY_JWT=6947823eb5deeccc7fcf863fc4dbd4649d8ef60057f482e31bcc241c6e537f98
      - GOOGLE_API_KEY=AIzaSyA8YrxzYR9Gix93tZ-x4aVIekH4EGoQhx4
      - ORIGIN=http://localhost:3000
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./back/
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./back/package.json
  
  frontend:
    environment:
      - REACT_APP_GOOGLE_API_KEY=AIzaSyA8YrxzYR9Gix93tZ-x4aVIekH4EGoQhx4
      - REACT_APP_API_URL=http://localhost:4000
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./front/
          target: /usr/src/app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./front/package.json