services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - backend-data:/usr/src/app/src/uploads
    mem_limit: 4g



  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    mem_limit: 4g

volumes:
  backend-data:
    external: true