services:
  backend:
    environment:
      - ORIGIN=http://142.93.100.162:3000
      - NODE_ENV=production

  frontend:
    environment:
      - REACT_APP_API_URL=http://142.93.100.162:4000
      - NODE_ENV=production